{
 "title": "Github Actions Runners",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Online Runners",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(github_runner_org_status{status=\"online\"})"
    }
   ]
  },
  {
   "title": "Offline Runners",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(github_runner_org_status{status=\"offline\"})"
    }
   ]
  },
  {
   "title": "Active Runners",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(github_runner_org_busy{busy=\"true\"})"
    }
   ]
  },
  {
   "title": "Idle Runners",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(github_runner_org_busy{busy=\"false\"})"
    }
   ]
  },
  {
   "title": "Active Runners",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "github_runner_org_busy{busy=\"true\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Active Runners by Labels",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(github_runner_org_busy{busy=\"true\"}) by(labels)",
     "legendFormat": "{{labels}}"
    }
   ]
  }
 ]
}