name: docker-push


on:
  release:
    types: [published]


jobs:
  docker:
    runs-on: ubuntu-latest

    if: ${{ startsWith(github.event.release.tag_name, 'prometheus-org-runner-exporter') != true }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            tchelovilar/github-org-runner-exporter:latest

      - name: Publish New Version
        if: ${{ github.event.action == 'published' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            tchelovilar/github-org-runner-exporter:${{ github.event.release.tag_name }}
